### ISSUE TITLE
Android tflite?

### ISSUE THREAD

**Issue by tjasmin111** [andreacoppari/ELSR-torch#1]
Interesting repo. I like to test it on Android. But do you have the tflite model? How can we run in on a phone?

**Comment by andreacoppari** [comment]
Hi, thanks for the interest.
I didn't upload a tflite model, but I used this pipeline:

[https://github.com/sithu31296/PyTorch-ONNX-TFLite](https://github.com/sithu31296/PyTorch-ONNX-TFLite)

to convert torch models to tflite.

I strongly recommend to re-train the model directly on TF and to train it on a better curated dataset (readme for more).

My initial idea was to create alongside a small camera app to test the model, but I kinda dropped (delayed) the project for time reasons.

Btw, this was a small university project and the effort (and the time!) was limited, and I never expected to get someone to reach me for this. Let me know if you need anything else, always here!

AC

**Comment by tjasmin111** [comment]
Thanks. I will try training it later.
I'm new to SR. But I want to do it for talking heads, like in video conferencing. Because the background is always static and head moves only, is there anything we can do to make it realtime? Any optimization we can do? Or just train on them is enough?

**Comment by andreacoppari** [comment]
> Is there anything we can do to make it realtime? Any optimization we can do?

The time for the generation of SR frame, aka model inference time, solely depends on the architecture that you're using (and on the hardware ofc). Training impacts on the results.

The model I shared is trained on bicubic downscaled videos, hence it performs realtime bicubic interpolation, if you have the resources to train on the original REDS dataset you should be getting some serious improvement without getting worse inference time.

> Or just train on them is enough?

Fine-tuning the model on your dataset might be a fast and power-efficient solution.

AC

Edit: broken reference

**Comment by tjasmin111** [comment]
I see, thanks. Yeah I noticed your results looks worse than the bicubic. So at most with best training it will look like bicubic right?

**Comment by andreacoppari** [comment]
Using my same dataset probably yes, but "worse" in terms of PNRR doesn't necessarily mean worse with other metrics such as NIQE or simply SSIM.

Results rely on training time, dataset and hyperparameters tuning, let me know if you get good results :)

**Comment by tjasmin111** [comment]
Got it. Do you recommend any other architecture that is more state of the art and more suitable for my realtime requirements and the uwecase I have?

**Comment by andreacoppari** [comment]
> Got it. Do you recommend any other architecture [...]? 

I'm no longer following low-power SR research, there should be many newer and more efficient architectures, but usually they don't share the weights, and training might get very expensive.

**Comment by tjasmin111** [comment]
Ok. I'll try your architecture :)
